### ISSUE TITLE
`setTime` from the `useTimer` hook?

### ISSUE THREAD

**Issue by jay-khatri** [thibaultboursier/use-timer#30]
Hi there. Is there a way to explicitly set the time to a specific point from the component that uses the hook? I have a component that is a video player, and would like to be able to skip +/- 5 seconds.

It seems like [this](https://github.com/thibaultboursier/use-timer/blob/master/src/useTimer.ts#L13) would do the trick, but its not exported.

**Comment by thibaultboursier** [comment]
Helo @jay-khatri,

**Comment by jay-khatri** [comment]
That'd be great! Thanks for the reply here 😄 .

**Comment by thibaultboursier** [comment]
I'll come back to you soon.

**Comment by thibaultboursier** [comment]
Hello @jay-khatri.

I just released **1.4.0** version, with new feature: **advanceTime**.
You can check the documentation and the test files to see how it works (it's quite simple).
You can also test it here: https://stackblitz.com/edit/use-timer

Tell me what do you think.

**Comment by jay-khatri** [comment]
Hi @thibaultboursier, appreciate the update! I'll probably incorporate this over the weekend; maybe I'll send over a demo when its ready 😄 .

**Comment by thibaultboursier** [comment]
Hi @jay-khatri, sûre, don't hesitate 😉
