### ISSUE TITLE
Milliseconds timer with endTime

### ISSUE THREAD

**Issue by andresbdo** [thibaultboursier/use-timer#35]
Hi, i am trying to use the timer with milliseconds but I couldnt.

this is what i've been trying

const { time, start, pause, reset, isRunning } = useTimer({
        initialTime: 1,
        endTime: 3.4,
        step: 0.1, 
        interval: 100,
    });

**Comment by thibaultboursier** [comment]
Hi @andresbdo, did you manage to solve your issue?

**Comment by andresbdo** [comment]
Hi @thibaultboursier.  No, i couldnt. I need the timer look like 1.1. I'm trying to put step on 0.1 with interval of 100 and a random endTime like Number(randomNumber.toFixed(1)) and work perfectly but time doesn´t stop. can you help me please?

**Comment by thibaultboursier** [comment]
@andresbdo Can you create example on StackBlitz to reproduce issue please?

**Comment by andresbdo** [comment]
https://stackblitz.com/edit/react-njfyyr?file=src/App.js

**Comment by thibaultboursier** [comment]
Thanks. What should be the correct behavior in your example?

**Comment by thibaultboursier** [comment]
Also, in your example, you don't use `useTimer` library. Can your provide an example with `useTimer` please?

**Comment by andresbdo** [comment]
It's updated now, im sorry.

**Comment by andresbdo** [comment]
I'm trying to make the counter stop at the randomNumber with the timer starting at 1.

randomNumber = 1.3

time:
1.0
1.1
1.2
1.3

stop

**Comment by thibaultboursier** [comment]
If you want the timer to stop at the random number:
- You must provide correct `endTime` value.
- The timer must arrive on this `endTime` value.
