### ISSUE TITLE
Would you consider a PR that adds a third state for the timer?

### ISSUE THREAD

**Issue by ervine13** [thibaultboursier/use-timer#38]
Hello!

Would you consider a PR being able to differentiate between being paused vs stopped vs running? Or should I just fork the repo?

Thanks

**Comment by thibaultboursier** [comment]
Hello @ervine13,

Thanks for opening this issue. It could be a good idea to have others states that just `isRunning`.
Can you give me an example of the kind of properties you would like to access when using this `useTimer` hook?

Have a nice day.

**Comment by ervine13** [comment]
@thibaultboursier , sorry for the delayed response. `isPaused` was the only one I could think of. At least for my use case.

If you're open to more significant change, you could create a `status` property that returns 3 values `active`, `paused`, `stopped`.

**Comment by thibaultboursier** [comment]
Hello @ervine13,

Very good idea to have a `status` property. It should make a breaking change and a new major release, as we currently return `isRunning` property, and we would remove it.

So, two choices to handle your point:

## 1. Return separate properties
We would return `isRunning` (maybe semantically better than `isActive`?), `isPaused`, `isStopped`.

## 2. Return a status string
We could create a `status` enum:
```ts
export type Status = 'RUNNING' | 'PAUSED' | 'STOPPED';
```
We would update `status` value inside reducer.

What do you think? Would you like to make a PR?

**Comment by ervine13** [comment]
@thibaultboursier I can create a PR to create a `status`

**Comment by thibaultboursier** [comment]
@ervine13 You rocks 🦸‍♂️

**Comment by thibaultboursier** [comment]
Hello @ervine13,

I approved your PR and merged in into `develop` branch. I'll merge it into `master` soon, and will make a new version `2.0.0`.
Then, we'll close this issue if it's OK for you.

Thanks ;-)

**Comment by ervine13** [comment]
Thanks, @thibaultboursier
