### ISSUE TITLE
Feature request: set initial status

### ISSUE THREAD

**Issue by robynm** [thibaultboursier/use-timer#73]
Hi, I was wondering if you would consider adding an optional parameter to initialize the timer with a status other than STOPPED?

I'm saving timer use to a db and would like to be able to return the timer to the last known state in the case of page refresh or network interruption.

I can submit a PR for this if you'd like. Thanks!

**Comment by thibaultboursier** [comment]
Hello @robynm,

It's a good idea. 
OK, don't hesitate to submit a PR ;-)

**Comment by thibaultboursier** [comment]
Merged into `develop` branch.

**Comment by Lechevallier** [comment]
Hi, I have the same need.

The only thing is that if I initialise my timer with the value saved in db (`initialTime: timeFromDB`), the `reset` function will reset to this value (which is logic).
A solution could be to pass an optional parameter to the `reset` function.

I will check your code and try to make a PR if you think its a good improvement

**Comment by Lechevallier** [comment]
Or a solution could be to have a function allowing to set the `time` directly, so I wouldn't have to use `initialTime`. What do you think could be the best option?

**Comment by Lechevallier** [comment]
Just realise `advanceTime` allows me to set the time when it's initialised to 0, sorry for the spam 🙈
(maybe exporting a `setTime` function would give more flexibility 😉)

Thanks for the amazing work btw! 💯

**Comment by Lechevallier** [comment]
Well it's still buggy this way, `play` will start from `initialTime`, not from the current.
Will try to open a PR
